FROM oven/bun:1.3.12 AS base
WORKDIR /app

FROM base AS prepare
WORKDIR /app
COPY . .
RUN bunx turbo@2.9.3 prune web --docker

FROM base AS builder
WORKDIR /app
COPY --from=prepare /app/out/json/ .
COPY --from=prepare /app/out/bun.lock ./bun.lock
RUN bun install --frozen-lockfile

COPY --from=prepare /app/out/full/ .
ENV NODE_ENV=production
RUN bun install --frozen-lockfile
RUN bunx turbo run build --filter=web

FROM base AS runner
USER bun
WORKDIR /app
ENV NODE_ENV=production

# Copy built app files and production dependencies
COPY --from=builder --chown=bun:bun /app/apps/web/.next ./apps/web/.next
COPY --from=builder --chown=bun:bun /app/apps/web/public ./apps/web/public
COPY --from=builder --chown=bun:bun /app/apps/web/package.json ./apps/web/package.json

# Copy monorepo node_modules and shared packages for runtime resolution
COPY --from=builder --chown=bun:bun /app/packages ./packages
COPY --from=builder --chown=bun:bun /app/node_modules ./node_modules
COPY --from=builder --chown=bun:bun /app/package.json ./package.json

EXPOSE 3000
ENTRYPOINT []
WORKDIR /app/apps/web
CMD ["../../node_modules/.bin/next", "start"]
